"""
v1/routers.py — Conversion / Prediction endpoints

POST /api/v1/prediction/upload      — загрузить файл + схему → создать job
GET  /api/v1/prediction/{job_id}    — статус / результат job
GET  /api/v1/prediction             — список job-ов текущего пользователя
"""

import os
import uuid
import json
import asyncio
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, File, Form, UploadFile, HTTPException, BackgroundTasks

from src.config   import settings
from src.database import add_history
from src.api.deps import get_current_user
from src.api.v1.schemas import ConvertRequest, ConvertResponse, JobResult, JobStatus, PipelineStep

router = APIRouter()

# In-memory job store (заменить на Redis/DB в проде)
_jobs: dict[str, dict] = {}


# ── POST /upload ──────────────────────────────────────────────────────
@router.post("/upload", response_model=ConvertResponse, status_code=202, summary="Загрузить файл и запустить конвертацию")
async def upload_and_convert(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(..., description="CSV / XLS / XLSX / PDF / DOCX / PNG / JPG"),
    target_schema: str = Form(..., description="JSON-строка с целевой схемой"),
    user=Depends(get_current_user),
):
    # Validate schema JSON
    try:
        schema_dict = json.loads(target_schema)
    except json.JSONDecodeError:
        raise HTTPException(status_code=422, detail="target_schema: невалидный JSON")

    # Save uploaded file
    os.makedirs(settings.UPLOAD_DIR, exist_ok=True)
    file_ext = os.path.splitext(file.filename or "file")[1]
    saved_name = f"{uuid.uuid4().hex}{file_ext}"
    saved_path = os.path.join(settings.UPLOAD_DIR, saved_name)

    contents = await file.read()
    with open(saved_path, "wb") as f:
        f.write(contents)

    # Create job
    job_id = uuid.uuid4().hex
    now = datetime.now(timezone.utc).isoformat()
    _jobs[job_id] = {
        "job_id":      job_id,
        "user_id":     user["id"],
        "status":      JobStatus.pending,
        "filename":    file.filename,
        "file_path":   saved_path,
        "file_format": file_ext.lstrip(".").upper() or "FILE",
        "target_schema": schema_dict,
        "records":     0,
        "tokens_used": 0,
        "retries":     0,
        "ts_code":     None,
        "json_output": None,
        "pipeline":    [],
        "error":       None,
        "created_at":  now,
        "finished_at": None,
    }

    # Run pipeline in background
    background_tasks.add_task(_run_pipeline, job_id, user["id"])

    return ConvertResponse(job_id=job_id)


# ── GET /{job_id} ─────────────────────────────────────────────────────
@router.get("/{job_id}", response_model=JobResult, summary="Статус и результат job")
async def get_job(job_id: str, user=Depends(get_current_user)):
    job = _jobs.get(job_id)
    if not job or job["user_id"] != user["id"]:
        raise HTTPException(status_code=404, detail="Job не найден")
    return JobResult(**{k: v for k, v in job.items() if k != "user_id" and k != "file_path" and k != "target_schema"})


# ── GET / — list jobs ─────────────────────────────────────────────────
@router.get("", response_model=list[JobResult], summary="Список задач пользователя")
async def list_jobs(user=Depends(get_current_user)):
    user_jobs = [j for j in _jobs.values() if j["user_id"] == user["id"]]
    return [
        JobResult(**{k: v for k, v in j.items() if k not in ("user_id", "file_path", "target_schema")})
        for j in sorted(user_jobs, key=lambda x: x["created_at"], reverse=True)
    ]


# ── Background pipeline (mock LLM) ────────────────────────────────────
async def _run_pipeline(job_id: str, user_id: int):
    """
    Имитирует pipeline: parse → generate → validate → done.
    TODO: заменить на реальный вызов GigaChat / LangGraph.
    """
    job = _jobs[job_id]

    def _step(name: str, status: str, msg: str = "", tokens: int = 0):
        job["pipeline"].append(PipelineStep(name=name, status=status, message=msg, tokens=tokens).dict())

    job["status"] = JobStatus.processing
    await asyncio.sleep(0.8)

    # Step 1 — parse file
    _step("parse_file", "done", f"schema_hint extracted from {job['filename']}", tokens=80)
    job["tokens_used"] += 80
    await asyncio.sleep(1.0)

    # Step 2 — generate code
    _step("generate_code", "done", "ts_code generated · attempt 1/3", tokens=210)
    job["tokens_used"] += 210
    job["ts_code"] = (
        "interface DealData {\n  dealId: string;\n  amount: number;\n  stage: string;\n}\n\n"
        "export default function(base64file: string): DealData[] {\n"
        "  // generated by GigaChat\n  return [];\n}"
    )
    await asyncio.sleep(0.8)

    # Step 3 — validate
    _step("validate_code", "done", "tsc ✓ · runtime ✓ · JSON shape ✓", tokens=50)
    job["tokens_used"] += 50
    await asyncio.sleep(0.4)

    # Step 4 — result
    job["json_output"] = [
        {"dealId": "DEAL-12345", "amount": 1000000, "stage": "Переговоры"},
        {"dealId": "DEAL-67890", "amount": 500000,  "stage": "Закрыта"},
        {"dealId": "DEAL-24680", "amount": 300000,  "stage": "В работе"},
    ]
    job["records"]     = len(job["json_output"])
    job["retries"]     = 1
    job["status"]      = JobStatus.done
    job["finished_at"] = datetime.now(timezone.utc).isoformat()
    _step("result", "done", f"{job['records']} records · valid")

    # Persist to history
    add_history({
        "user_id":    user_id,
        "job_id":     job_id,
        "status":     "valid",
        "filename":   job["filename"],
        "file_format": job["file_format"],
        "tokens":     job["tokens_used"],
        "retries":    job["retries"],
        "records":    job["records"],
        "time":       job["finished_at"],
    })
